### ISSUE TITLE
Running into below error TypeError: Invalid argument(s) 'async_creator' sent to create_engine(), using configuration PGDialect_asyncpg/AsyncAdaptedQueuePool/Engine. Please check that the keyword arguments are appropriate for this combination of components.

### ISSUE THREAD

**Issue by ng-tarun** [googleapis/langchain-google-cloud-sql-pg-python#118]
I am using gcp cloud sql postgres for storing memory. Till april 15th, it is working fine. But, from today i am running into below 
issue. 
TypeError: Invalid argument(s) 'async_creator' sent to create_engine(), using configuration PGDialect_asyncpg/AsyncAdaptedQueuePool/Engine. Please check that the keyword arguments are appropriate for this combination of components.

# code
from langchain_google_cloud_sql_pg import PostgresEngine

![postgres error](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/assets/117971004/713c0de9-b58d-4f92-a2c9-456301b75cf6)

My packages are:
langchain==0.1.13
langchain-community==0.0.29
langchain-core==0.1.33
langchain-google-genai==0.0.6
langchain-google-vertexai==0.1.1
langchain-google-cloud-sql-pg==0.2.0

Help me in resolving the issue.

**Comment by averikitsch** [comment]
Hi @ng-tarun, can you share more of your code and your dependencies (use `pip freeze`)? This may be an issue with how the engine is being instantiated or if it is being instantiated multiple times. THis could also be related to https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/issues/1057 where the SQLAlchemy version is <v2.0.

**Comment by jackwotherspoon** [comment]
@ng-tarun This error is when you are using a version of SQLAlchemy less than `v2.0.16`, you can check you SQLAlchemy version by running `pip show SQLAlchemy`.

I added support for the `async_creator` in SQLAlchemy [v2.0.16](https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_2_0_16) so maybe there is a dep conflict restricting your version.

Adding `SQLAlchemy==2.0.29` or any version after 2.0.16 to your requirements.txt should fix this.

**Comment by averikitsch** [comment]
Please re-open if you continue to experience this issue.
