### ISSUE TITLE
Support Langchain 0.2.0

### ISSUE THREAD

**Issue by elmdecoste** [googleapis/langchain-google-cloud-sql-pg-python#132]
With the release of Langchain 0.2.0, many of the other libraries that provide connectors and other libraries (e.g. `langchain_experimental`) require support for 0.2.0. Our team uses the pg connector provided here and the libraries are currently incompatible with the rest of our libraries.

**Comment by averikitsch** [comment]
I have released version 0.5.0 that supports LangChain v0.2.0. This should be available within the hour. Please reopen this issue if you continue to experience this issue.
