### ISSUE TITLE
Create collection with schema 

### ISSUE THREAD

**Issue by trevorwjames** [googleapis/langchain-google-cloud-sql-pg-python#175]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Currently we are trying to place our collections inside a specific schema based on the app, rather than a public schema. So right now this is a blocker for our app to progress

 **Describe the solution you'd like**
We would like to be able to specify the schema with the collection name. Right now if I specify <schema>.<collection> as a single string when calling init_vectorstore_table it just creates the table as "schema.collection"

 **Describe alternatives you've considered**
I right now the only alternatives would be creating a table through pure sql and then referencing that table when creating a vectorstore. 

 **Additional context**
This is the same Trevor James from Ford Motor Company that has been messaging Kurtis, Averi and Tabby. Ford does not allow me to file issues on my company github account, so I am filiing using this one.

**Comment by jackwotherspoon** [comment]
Similar ask from AlloyDB repo https://github.com/googleapis/langchain-google-alloydb-pg-python/issues/95
