### ISSUE TITLE
Google IAM Credentials Path in PostgresEngine#from_instance(...)

### ISSUE THREAD

**Issue by amitjoy** [googleapis/langchain-google-cloud-sql-pg-python#83]
I think instead of relying on default credentials for the current environment, it would be much more flexible to provide a credentials path in the `PostgresEngine.from_instance(..)` instead. The default credentials require consumers to set the necessary environment variable as well. As an added feature, the `credentials path` could also be used and you can retrieve the `Credentials` instance using `Credentials.from_service_account_file`

**Comment by jackwotherspoon** [comment]
I am going to close this for several reasons.

1. Using ADC credentials from the environment is much more flexible than a credentials path. (aka. Serverless applications will run without any additional config, local devs can use `gcloud application-default login`, etc.)
2. Credentials path is mainly for service account key files which are becoming more and more widely discouraged.
3. Credentials path is supported via ADC by setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable
4. `Credentials.from_service_account_file` can be used via the `from_engine` method as @averikitsch pointed out in the previous comment.

Happy to discuss further if need be 😄
